scenarios:

  accelerated_pv:
    name: "Acceleration PV"
    description: "Ajout PV + BESS modere"
    params:
      delta_pv_gw: 20
      delta_bess_power_gw: 5
      delta_bess_energy_gwh: 20

  electrification:
    name: "Electrification forte"
    description: "Demande +15%, dont hausse midi et soir"
    params:
      delta_demand_pct: 15
      delta_demand_midday_gw: 8
      delta_demand_evening_gw: 3

  high_co2:
    name: "CO2 eleve"
    description: "EUA constant a 120 EUR/t"
    params:
      co2_price_eur_t: 120

  high_gas:
    name: "Gaz eleve"
    description: "TTF constant a 50 EUR/MWh_th"
    params:
      gas_price_eur_mwh: 50

  nuclear_reduction_fr:
    name: "Reduction must-run FR"
    description: "Must-run -10 GW, compensation PV/Wind"
    params:
      delta_must_run_gw: -10
      delta_pv_gw: 15
      delta_wind_onshore_gw: 10

  flex_massive:
    name: "Flex massive"
    description: "BESS +15 GW / 60 GWh + PSH +3 GW + exports +5GW"
    params:
      delta_bess_power_gw: 15
      delta_bess_energy_gwh: 60
      delta_psh_pump_gw: 3
      delta_export_max_gw: 5

  combined_stress:
    name: "Stress combine"
    description: "PV x2 + demande stagnante + flex faible"
    params:
      delta_pv_gw: 25
      delta_demand_pct: 0
      delta_bess_power_gw: 1
      delta_bess_energy_gwh: 4
